"use client";

import { BulletCard, PageFooter, PageHero, Reveal, Section, Steps } from "../components/service-page-shared";

const conditions = [
  { id: "anxiety", title: "Anxiety Disorders", description: "Anxiety disorders may involve persistent worry, panic, avoidance, restlessness, racing thoughts, or physical symptoms such as a racing heart.", examples: ["Generalized anxiety disorder (GAD)", "Social anxiety disorder", "Panic disorder", "Specific phobias"], care: "Care may include clinical evaluation, cognitive behavioral therapy (CBT), medication when appropriate, and strategies for managing anxiety symptoms." },
  { id: "mood", title: "Mood Disorders", description: "Mood disorders can affect energy, motivation, sleep, and emotional stability. Some involve persistent depression, while bipolar disorders may involve depressive and manic or hypomanic episodes.", examples: ["Major depressive disorder (MDD)", "Bipolar I disorder", "Bipolar II disorder", "Cyclothymic disorder"], care: "Treatment may include medication management, psychotherapy, ongoing symptom monitoring, and an individualized plan for mood stability." },
  { id: "psychotic", title: "Psychotic Disorders", description: "Psychotic disorders may affect perception, thinking, and a person's interpretation of reality. Symptoms can include hallucinations, delusions, or disorganized thinking.", examples: ["Schizophrenia", "Schizoaffective disorder", "Other psychosis-related symptoms"], care: "Early assessment and continuity of care are important. Treatment may involve antipsychotic medication, supportive psychotherapy, and coordination with other services as appropriate." },
  { id: "ocd", title: "Obsessive-Compulsive Disorder (OCD)", description: "OCD involves unwanted, intrusive thoughts or images (obsessions) and repetitive behaviors or mental rituals (compulsions) that may interfere with everyday life.", examples: ["Intrusive thoughts", "Checking or reassurance rituals", "Contamination-related fears", "Repetitive mental compulsions"], care: "Evidence-based approaches can include exposure and response prevention (ERP), a specialized form of CBT, and certain medications such as SSRIs. Referral for specialized ERP may be appropriate." },
  { id: "ptsd", title: "Post-Traumatic Stress Disorder (PTSD)", description: "PTSD can develop after exposure to trauma and may involve intrusive memories, nightmares, avoidance, changes in mood, and heightened alertness.", examples: ["Flashbacks or intrusive memories", "Avoidance of trauma reminders", "Sleep disturbances", "Hypervigilance and emotional distress"], care: "Treatment may involve trauma-focused psychotherapy such as cognitive processing therapy, prolonged exposure, or EMDR, and medication when appropriate. Availability of specific therapies should be confirmed with the practice." },
  { id: "personality", title: "Personality Disorders", description: "Personality disorders involve longstanding patterns of thinking, emotional experience, behavior, and relating to others that can cause distress or impair functioning.", examples: ["Borderline personality disorder (BPD)", "Narcissistic personality disorder (NPD)", "Antisocial personality disorder (ASPD)", "Other personality-related difficulties"], care: "Treatment often emphasizes psychotherapy, including approaches such as dialectical behavior therapy (DBT) for BPD. Medication may be considered for co-occurring symptoms or conditions rather than as a direct cure for a personality disorder." },
];

export default function ConditionsTreatedPage() {
  return <main className="overflow-hidden bg-white">
    <PageHero eyebrow="Transcending Psychiatry · Ages 12+" title="Conditions" highlight="Treated" description="Individualized mental health care for adolescents and adults ages 12 and older in New York and New Jersey. Explore the conditions we assess and the treatment approaches that may be considered." />
    <Section eyebrow="Compassionate care" title="Understanding your mental health needs">
      <Reveal><p className="max-w-4xl text-lg leading-9 text-[#6d6661]">Transcending Psychiatry provides psychiatric assessment and individualized treatment planning for a range of mental health conditions, including anxiety disorders, mood disorders, psychotic disorders, OCD, PTSD, and personality disorders. Treatment recommendations depend on a careful evaluation of symptoms, medical history, goals, and clinical needs.</p></Reveal>
      <div className="mt-10 flex flex-wrap gap-3">{conditions.map(c => <a key={c.id} href={`#${c.id}`} className="rounded-full border border-[#f1dac9] bg-[#fff8f2] px-5 py-3 text-sm font-semibold text-[#b75a27] transition hover:-translate-y-0.5 hover:bg-[#ff7426] hover:text-white">{c.title} ↓</a>)}</div>
    </Section>
    {conditions.map((c, i) => <section key={c.id} id={c.id} className={`${i % 2 ? "bg-white" : "bg-[#fff8f2]"} scroll-mt-24 px-6 py-20 sm:py-24`}><div className="mx-auto max-w-7xl"><Reveal><p className="text-xs font-bold uppercase tracking-[0.24em] text-[#d9692c]">Condition {String(i + 1).padStart(2, "0")}</p><h2 className="mt-4 text-3xl font-semibold tracking-tight text-[#292624] sm:text-5xl">{c.title}</h2><p className="mt-6 max-w-4xl text-lg leading-9 text-[#6d6661]">{c.description}</p></Reveal><div className="mt-10 grid gap-6 lg:grid-cols-2"><BulletCard title="Common presentations" bullets={c.examples} /><Reveal><div className="h-full rounded-3xl border border-[#eeded1] bg-white p-7 sm:p-9"><h3 className="text-2xl font-semibold text-[#2b2826]">Treatment approaches</h3><p className="mt-5 text-[16px] leading-9 text-[#6d6661]">{c.care}</p><p className="mt-6 text-sm leading-7 text-[#a15e38]">Your provider will discuss which options are clinically appropriate and available for your needs.</p></div></Reveal></div></div></section>)}
    <Section eyebrow="Assessment first" title="How we evaluate mental health conditions">
      <div className="grid gap-6 lg:grid-cols-2"><BulletCard title="A comprehensive picture" bullets={["Discussion of symptoms and their impact on daily life", "Review of psychiatric, medical, and family history", "Screening tools or further evaluation when appropriate", "Consideration of cultural, environmental, and personal factors"]} /><BulletCard title="A collaborative plan" bullets={["Explain clinical findings and possible diagnoses", "Discuss treatment options, risks, and benefits", "Coordinate referrals or additional services when needed", "Review progress and adapt the plan over time"]} /></div>
    </Section>
    <Section eyebrow="Why Transcending Psychiatry" title="Care built around the individual" tinted>
      <div className="grid gap-6 lg:grid-cols-2"><BulletCard title="Our approach" bullets={["Compassionate, nonjudgmental conversations", "Individualized evaluations and medication management", "Trauma-informed attention to patient needs", "Respect for privacy and personal goals"]} /><BulletCard title="What to expect" bullets={["An opportunity to discuss your concerns", "Thoughtful review of treatment options", "Clear communication about next steps", "Support for adolescents and adults ages 12 and older"]} /></div>
    </Section>
    <Section eyebrow="Getting started" title="Your path to care">
      <Steps items={[{ title: "Schedule an evaluation", text: "Contact the practice to discuss appointment availability and your initial concerns." }, { title: "Build a personalized plan", text: "Work with your psychiatric provider to review assessment findings and possible treatment approaches." }, { title: "Continue with support", text: "Follow up as recommended, discuss your progress, and adjust your plan when needed." }]} />
      <Reveal className="mt-8"><p className="max-w-4xl text-sm leading-7 text-[#756b65]">Information on this page is educational and does not replace an individualized diagnosis or medical advice. Specific therapies and services may require referral or coordination with another qualified clinician.</p></Reveal>
    </Section>
    <PageFooter current="/conditions-treated" />
  </main>;
}
